In [3]:
import tensorflow as tf

In [9]:
# Eager execution, default mode in tf2
a = tf.constant([1, 2, 3])
b = tf.constant([0, 0, 1])
c = tf.add(a, b)
print(c)
print(c.numpy())

tf.Tensor([1 2 4], shape=(3,), dtype=int32)
[1 2 4]


In [12]:
# Eager execution
def compute(a, b, c):
    d = a * b + c
    e = a * b * c
    return d, e

# At the 1st time the function is called, the eager mode will compute the value instead of create graph
compute(a, b, c)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 7], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 0,  0, 12], dtype=int32)>)

In [15]:
# Creating graph, it will turn eager code into a graph, allowing automatic optimization
@tf.function
def compute(a, b, c):
    d = a * b + c
    e = a * b * c
    return d, e

compute(a, b, c)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 7], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 0,  0, 12], dtype=int32)>)

In [49]:
# Backpropagating errors using the gradient tape
A, B = tf.constant(3.0), tf.constant(6.0)
X = tf.Variable(20.0)
loss = tf.math.abs(A * X - B)
print(loss)

tf.Tensor(54.0, shape=(), dtype=float32)


In [50]:
def train_step():
    with tf.GradientTape() as tape:
        loss = tf.math.abs(A * X - B)
    dX = tape.gradient(loss, X)
    print('X = {:.2f}, dX = {:.2f}, loss = {:.2f}'.format(X.numpy(), dX, loss))
    X.assign(X - dX)
    
for i in range(7):
    train_step()

X = 20.00, dX = 3.00, loss = 54.00
X = 17.00, dX = 3.00, loss = 45.00
X = 14.00, dX = 3.00, loss = 36.00
X = 11.00, dX = 3.00, loss = 27.00
X = 8.00, dX = 3.00, loss = 18.00
X = 5.00, dX = 3.00, loss = 9.00
X = 2.00, dX = 0.00, loss = 0.00
